# Generated by Django 5.0.2 on 2024-02-29 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0027_remove_domain_logo_image_techstack_logo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="creative_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="innovative_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="performance_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="societal_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="userfriendly_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="college.college"
            ),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="dept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="college.department"
            ),
        ),
    ]
