# Generated by Django 5.0.2 on 2024-02-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0029_alter_project_current_yr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecttask",
            name="total_score",
        ),
        migrations.AddField(
            model_name="task",
            name="task_total_score",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
