# Generated by Django 5.0.2 on 2024-02-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0030_remove_projecttask_total_score_task_task_total_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image_1",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("InProgress", "In Progress"),
                    ("Submitted", "Submitted"),
                    ("Reassigned", "Re Assigned"),
                    ("Verified", "Verified"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
