# Generated by Django 5.0.2 on 2024-03-04 10:30

import college.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0031_alter_project_image_1_alter_project_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.IntegerField(default=college.models.current_year)),
                ('college', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department')),
                ('panel_member_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_member_1', to='college.mentor')),
                ('panel_member_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_member_2', to='college.mentor')),
                ('panel_member_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_member_3', to='college.mentor')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='panel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.panel'),
        ),
    ]
