# Generated by Django 5.0.2 on 2024-03-05 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0032_panel_project_panel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('notification_date', models.DateField()),
                ('task_total_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('InProgress', 'In Progress'), ('Submitted', 'Submitted'), ('Verified', 'Verified')], default='Pending', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.project')),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.task')),
                ('review_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.review')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.review')),
                ('timeline_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.timeline')),
            ],
        ),
    ]
