# Generated by Django 5.0.2 on 2024-03-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0033_review_projectreview_timelinereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='task_total_score',
            new_name='review_total_score',
        ),
    ]
