# Generated by Django 5.0.2 on 2024-03-07 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0034_rename_task_total_score_review_review_total_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creative_score',
            new_name='coding_standards_score',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='innovative_score',
            new_name='communications_presentation_score',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='performance_score',
            new_name='innovation_score',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='userfriendly_score',
            new_name='national_representation_score',
        ),
        migrations.RenameField(
            model_name='projectreview',
            old_name='score',
            new_name='score1',
        ),
        migrations.RemoveField(
            model_name='projectreview',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='projectreview',
            name='response',
        ),
        migrations.RemoveField(
            model_name='projectreview',
            name='status',
        ),
        migrations.RemoveField(
            model_name='projectreview',
            name='task_name',
        ),
        migrations.AddField(
            model_name='project',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='panel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.panel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectreview',
            name='score2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectreview',
            name='score3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectreview',
            name='score4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='finalize_button_activated',
            field=models.BooleanField(default=False),
        ),
    ]
