# Generated by Django 5.0.2 on 2024-03-07 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0035_rename_creative_score_project_coding_standards_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='panel_member_4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='panel_member_4', to='college.mentor'),
            preserve_default=False,
        ),
    ]
