# Generated by Django 5.0.2 on 2024-03-07 02:34

import college.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0036_panel_panel_member_4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='current_year',
            new_name='current_y',
        ),
        migrations.AddField(
            model_name='panel',
            name='admission_year',
            field=models.IntegerField(choices=college.models.year_choices, default=college.models.current_year),
        ),
    ]
