# Generated by Django 5.0.2 on 2024-03-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0038_remove_projectreview_panel_alter_panel_current_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='registration_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='origin_country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='regisrtation_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
