# Generated by Django 5.0.3 on 2024-03-08 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0040_alter_projecttask_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="member_details_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_1",
                to="college.student",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="member_details_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_2",
                to="college.student",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="member_details_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_3",
                to="college.student",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="member_details_4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_4",
                to="college.student",
            ),
        ),
        migrations.CreateModel(
            name="PendingProjectStudentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("stundet_no", models.IntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="college.project",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="college.student",
                    ),
                ),
            ],
        ),
    ]
