# Generated by Django 5.0.3 on 2024-03-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0041_alter_project_member_details_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pendingprojectstudentrequest",
            old_name="stundet_no",
            new_name="stundent_no",
        ),
    ]
