# Generated by Django 5.0.3 on 2024-03-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0043_rename_stundent_no_pendingprojectstudentrequest_student_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="college",
            name="college_type",
        ),
        migrations.RemoveField(
            model_name="college",
            name="registration_no",
        ),
        migrations.RemoveField(
            model_name="company",
            name="origin_country",
        ),
        migrations.RemoveField(
            model_name="company",
            name="regisrtation_no",
        ),
    ]
