# Generated by Django 5.0.2 on 2024-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0044_remove_college_college_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.TextField()),
                ('column2', models.CharField(max_length=20)),
                ('column3', models.TextField()),
                ('column4', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='copyrighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
